/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DocsExmaple {
        /**
          * Centers examples
         */
        "centered": boolean;
        /**
          * Web Component markup encoded as URI component
         */
        "code": string;
        /**
          * CSS component markup encoded as URI component.
         */
        "codeCssComponent": string;
        /**
          * Opens code view on initial load.
         */
        "opened": boolean;
        /**
          * Custom show-container styles.
         */
        "styles": string;
    }
    interface DocsLayout {
    }
    interface DocsMain {
    }
    interface SageInput {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLDocsExmapleElement extends Components.DocsExmaple, HTMLStencilElement {
    }
    var HTMLDocsExmapleElement: {
        prototype: HTMLDocsExmapleElement;
        new (): HTMLDocsExmapleElement;
    };
    interface HTMLDocsLayoutElement extends Components.DocsLayout, HTMLStencilElement {
    }
    var HTMLDocsLayoutElement: {
        prototype: HTMLDocsLayoutElement;
        new (): HTMLDocsLayoutElement;
    };
    interface HTMLDocsMainElement extends Components.DocsMain, HTMLStencilElement {
    }
    var HTMLDocsMainElement: {
        prototype: HTMLDocsMainElement;
        new (): HTMLDocsMainElement;
    };
    interface HTMLSageInputElement extends Components.SageInput, HTMLStencilElement {
    }
    var HTMLSageInputElement: {
        prototype: HTMLSageInputElement;
        new (): HTMLSageInputElement;
    };
    interface HTMLElementTagNameMap {
        "docs-exmaple": HTMLDocsExmapleElement;
        "docs-layout": HTMLDocsLayoutElement;
        "docs-main": HTMLDocsMainElement;
        "sage-input": HTMLSageInputElement;
    }
}
declare namespace LocalJSX {
    interface DocsExmaple {
        /**
          * Centers examples
         */
        "centered"?: boolean;
        /**
          * Web Component markup encoded as URI component
         */
        "code": string;
        /**
          * CSS component markup encoded as URI component.
         */
        "codeCssComponent"?: string;
        /**
          * Opens code view on initial load.
         */
        "opened"?: boolean;
        /**
          * Custom show-container styles.
         */
        "styles"?: string;
    }
    interface DocsLayout {
    }
    interface DocsMain {
    }
    interface SageInput {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "docs-exmaple": DocsExmaple;
        "docs-layout": DocsLayout;
        "docs-main": DocsMain;
        "sage-input": SageInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "docs-exmaple": LocalJSX.DocsExmaple & JSXBase.HTMLAttributes<HTMLDocsExmapleElement>;
            "docs-layout": LocalJSX.DocsLayout & JSXBase.HTMLAttributes<HTMLDocsLayoutElement>;
            "docs-main": LocalJSX.DocsMain & JSXBase.HTMLAttributes<HTMLDocsMainElement>;
            "sage-input": LocalJSX.SageInput & JSXBase.HTMLAttributes<HTMLSageInputElement>;
        }
    }
}
